services:
  dhcpd:
    build:
      context: ./dhcpd
    network_mode: host
    ports:
    - 67:67/udp
    restart: always
    volumes:
    - ./dhcpd/data/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
    - ./dhcpd/data/leases:/var/lib/dhcp:rw
version: '3.0'
