version: "3.0"

services:
  nextcloud:
    image: nextcloud
    env_file: /var/docker/config/nextcloud/nextcloud.env
    networks:
      - default
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:nextcloud.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=80
    volumes:
      - /var/docker/data/nextcloud/:/var/www/html
      - /var/docker/data/nextcloud/apps:/var/www/html/custom_apps
      - /var/docker/data/nextcloud/config:/var/www/html/config
      - /var/docker/data/nextcloud/data:/var/www/html/data

  db:
    image: mariadb:10
    env_file: /var/docker/config/nextcloud/nextcloud.env
    networks:
      - default
    volumes:
      - /var/docker/runtime/nextcloud/db:/var/lib/mysql

  redis:
    image: redis:alpine
    networks:
      - default
    volumes:
      - /var/docker/runtime/nextcloud/redis:/data

  solr:
    image: solr:6-alpine
    networks:
      - default
    volumes:
    - /var/docker/runtime/nextcloud/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant

  cron:
    image: nextcloud
    volumes:
      - /var/docker/data/nextcloud/:/var/www/html
    user: www-data
    networks:
      - default
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'

networks:
  traefik_public:
    external: true
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.12.0/24
