services:
  app:
    image: geitaguy/suitecrm
    env_file:
      - /var/docker/config/suitecrm/db.env
      - /var/docker/config/suitecrm/suitecrm.env
    tty: true
    volumes:
      - suitecrm:/var/www/html
    deploy:
      labels:
        - traefik.frontend.rule=Host:crm.geitaguy.net
        - traefik.docker.network=traefik_public
        - traefik.port=80
        - traefik.enable=true
    networks:
      - traefik_public
      - default

  db:
    image: mariadb
    env_file:
      - /var/docker/config/suitecrm/db.env
    volumes:
      - /var/docker/runtime/suitecrm/db:/var/lib/mysql:rw

volumes:
  suitecrm:

networks:
  traefik_public:
    external: true
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.21.0/24

version: '3.0'
