version: '3'

services:
  mail:
    image: tvial/docker-mailserver:latest
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - /var/docker/data/mailserver/maildata:/var/mail
      - /var/docker/data/mailserver/mailstate:/var/mail-state
      - /var/docker/data/mailserver/config:/tmp/docker-mailserver
      - /var/docker/data/mailserver/letsencrypt:/etc/letsencrypt
    env_file: /var/docker/config/mailserver/mailserver.env
    networks:
      - internal
    deploy:
      replicas: 1

    rainloop:
    image: hardware/rainloop
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:rainloop.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=8888
    volumes:
      - /var/docker/data/mailserver/rainloop:/rainloop/data

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.2.0/24
