version: "3"
services:
  app:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/data/portainer:/data
    networks:
      - default
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.frontend.rule=Host:portainer.geitaguy.net
        - traefik.port=9000
      placement:
        constraints: [node.role == manager]
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000/tcp
networks:
  traefik_public:
    external: true
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.2.0/24
